name: testing the code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: create file
        run: |
          mkdir app
          echo "Hello ashish" >> app/index.html
          cat app/index.html

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: application
          path: app/

      - name: accesiing the artifact
        uses: actions/download-artifact@v4
        with: 
          name: application

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: accessin thr download again 
        uses: actions/download-artifact@v4
        with: 
          name: application