name: testing the code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: create file
        run: |
          mkdir app
          echo "Hello ashish" >> app/index.html
          cat app/index.html

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: applciation
          path: app/